name: Deploy Kuleta Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: kuleta-website
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name:  Regenerate the Prisma client
        run: pnpm prisma generate

      - name: Copy environment variable
        run: cp -rf ../.env.template ./.env

      - name: Remove old build
        run: rm -rf .next

      - name: Build project
        run: pnpm run build

      - name: Start project using PM2
        run: pm2 start kuleta-website

      - name: PM2 instance info
        run: pm2 info kuleta-website
